version: '3'

services:
  web:
    build: .
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
    env_file:
      - ./.env
    ports:
      - 8000:8000
